# data_definitions.py

measure_names = [
    "Premium Efficiency Toilets, 0.8 gallons per flush (gpf)",
    "Small Tankless Water Heater, Tier 3 (UEF>=0.92), High Draw",
    "Tankless Water Heaters",
    "Duct Seal and Test, Residential, High (40% to 12%) SFm & MFm post 2006",
    "Duct Seal and Test, Residential, High (40% to 12%) SFm & MFm pre 2006",
    "Pool Heaters",
    "Existing Equipment",
    "Energy Star Dryer",
    "Smart Hose Bib Controller",
    "Smart Irrigation Water Controller – 8 Stations",
    "High Efficiency Toilets, 1.0 gpf",
    "Direct Mail Kit - Faucet Aerator for Commercial Buildings, Public Lavatory - 0.5 GPM Flow Rate AOE",
    "Therm-Based Compensation",
    "Duct Seal and Test, Residential, Medium (25% to 12%) SFm & MFm post 2006",
    "Return Duct Retrofit (total leakage reduction 50% to 15%)",
    "DHW Loop Controller, Multifamily, 10 Units, Gas",
    "DHW Loop Controller, Multifamily, 5 Units, Gas",
    "DHW Loop Controller, Multifamily, 45 Units, Gas",
    "Incentive Adjustment/Correction",
    "Crossover Duct Replacement (total leakage reduction 35% to 15%)",
    "DHW Loop Controller, Multifamily, 25 Units, Gas",
    "Small Tankless Water Heater, Tier 4 (UEF>=0.96), High Draw",
    "Small Tankless Water Heater, Tier 2 (UEF>=0.87), High Draw",
    "DHW Loop Controller, Multifamily, 20 Units, Gas",
    "Small Tankless Water Heater, Tier 2 (UEF>=0.87),Medium Draw",
    "Commercial Fryer, Gas, Tier 1 NR",
    "HW Heater Pipe Sleeve, Indoor",
    "Water Heater Installation",
    "Tubspout & Thermostatic Shut-off Showerhead; 1.5 GPM (SF)",
    "Small Tankless Water Heater, Tier 1 (UEF>=0.81), High Draw",
    "Duct Seal and Test, Mobile Home, High (35% to 15%)",
    "Faucet Aerator, Bathroom Sink, 1.0 gpm - MH",
    "Residential Smart Thermostat - DI",
    "HW Heater Pipe Sleeve, Outdoor",
    "Duct Seal and Test, Residential, Medium (25% to 12%) SFm & MFm pre 2006",
    "Duct Seal and Test, Mobile Home, Medium (25% to 15%)",
    "Faucet Aerator, Bathroom Sink, 1.0 gpm - SF",
    "DHW Loop Controller, Multifamily, 30 Units, Gas",
    "Commercial Natural Gas Pool Heater",
    "Modulating Gas Valve for Com Dryers up to 200 lbs cap AOE",
    "ENERGY STAR® Solar Thermal Water Heating System",
    "Faucet Aerator, Kitchen Sink, 1.5 gpm - SF",
    "Low Flow Showerhead, 1.5 gpm",
    "DHW Loop Controller, Multifamily, 15 Units, Gas",
    "Tank Insulation - High Temperature Applic. (LF) 2 in, Outdoor",
    "DHW Loop Controller, Multifamily, 40 Units, Gas",
    "DHW Loop Controller, Multifamily, 50 Units, Gas",
    "DHW Loop Controller, Multifamily, 35 Units, Gas",
    "Efficient Residential Gas Oven",
    "Fireplace Insert",
    "Storage Water Heaters",
    "Central System Gas Boiler Tier II (>=96%TE)",
    "Pool Cover",
    "Therm Kit Request",
    "Steam Trap Replacement - Commercial/Other BRO-Op",
    "Central System Tankless Water Heater Tier II (>=96%TE)",
    "Attic Insulation R-19",
    "Attic Insulation R-30",
    "Attic Insulation R-11",
    "Low Flow Showerhead, 1.5 gpm - MH",
    "Thermostatic Shower Valve",
    "Commercial Tankless Water Heater",
    "High Efficiency Furnace, Residential, AFUE 97%-VSM,SFm",
    "Smart Irrigation Water Controller – 16 Stations",
    "Central System Tankless Water Heater Tier II (>=90%TE)",
    "Attic Insulation R-38",
    "Residential Smart Thermostat-DI",
    "Central System Tankless Water Heater Tier I (>=90%TE)",
    "Process Boiler",
    "Low Flow Showerhead, 1.5 gpm NR",
    "Faucet Aerator, Kitchen Sink, 1.5 gpm",
    "Low Flow Pre-Rinse Spray Valve, 0.75 - 1.07 GPM NR",
    "Space Heating Boilers, >= 300 kBTHu",
    "Commercial Fryers",
    "Natural Gas Pool Heater >=84% TE",
    "High Efficiency Furnace, Residential, AFUE 95%-VSM,SFm",
    "Central System Gas Boiler Tier I (>=84%TE)",
    "Public Kicker",
    "Small Tankless Water Heater, Tier 2 (UEF>=0.87), Medium Draw",
    "Tank Insulation - Low Temperature Applic. (LF) 2 in, Indoor",
    "Small Tankless Water Heater, Tier 3 (UEF>=0.95), Medium Draw",
    "EE Kits",
    "Process Boilers, Condensing Economizer, AOE"
]

installers = [
    "Installer 7136",
    "Installer 7316",
    "Installer 7135",
    "Installer 7137",
    "Installer 7497",
    "Installer 7543",
    "Installer 7153",
    "Installer 7301",
    "Installer 7536",
    "Installer 7541",
    "Installer 7148",
    "Installer 7542",
    "Installer 7492",
    "Installer 7539",
    "Installer 7520",
    "Installer 7453",
    "Installer 7439",
    "Installer 7532",
    "Installer 7147",
    "Installer 7533",
    "Installer 7264",
    "Installer 7529",
    # ... Add any additional installer names here ...
]
